# -*- coding: utf-8 -*-
"""Drugs4Covid - Solr Corpus and Language Model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1awDkPtxY8YrDJMrnsOyFO-QLnM9iy86Z
"""



# Commented out IPython magic to ensure Python compatibility.

import pandas as pd
import numpy as np
import re
import nltk
from tqdm.auto import tqdm

#!pip install transformers


from transformers import RobertaTokenizer
from tqdm.auto import tqdm
import os


model_name='d4c_lm'

"""## Tokenizer"""

from pathlib import Path
paths = [str(x) for x in Path('/home/s730/PROJECT/data/').glob('*.txt')]

from tokenizers import ByteLevelBPETokenizer

tokenizer = ByteLevelBPETokenizer()

tokenizer.train(files=paths, vocab_size=30_522, min_frequency=2,
                special_tokens=['<s>', '<pad>', '</s>', '<unk>', '<mask>'])



os.mkdir('./'+model_name)

tokenizer.save_model(model_name)








